SYSCALL_C_FILES != ls syscalls/*.gen.c
SRCS = krf.c syscalls.c ../config.c ../krf.c $(SYSCALL_C_FILES) vnode_if.h
KMOD = krf

# NOTE(ww): Clear the default CFLAGS flags passed in the top-level Makefile.
# bsd.kmod.mk will do everything right for us.
# TODO(ww): Figure out why .unexport and .undef don't work here.
CFLAGS :=

.include <bsd.kmod.mk>
