all: "every syscall supported by KRF"
mm: "memory management syscalls"
fs: "filesystem interaction syscalls"
io: "general input/output syscalls"
proc: "process and task management syscalls"
time: "time and clock syscalls"
net: "socket and network syscalls"
ipc: "interprocess communication syscalls"
sys: "system configuration and state syscalls"
sched: "scheduling syscalls"
